version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 54321
      MYSQL_DATABASE: kartverket
      MYSQL_USER: root
      MYSQL_PASSWORD: 54321
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend


  kartverk.mvc:
    image: ${DOCKER_REGISTRY-}kartverkmvc
    build:
      context: .
      dockerfile: Kartverk.Mvc/Dockerfile
    ports:
      - "5001:8081"
    depends_on:
      - mariadb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=server=mariadb;database=kartverket;user=root;password=54321;
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend: