name: Build .NET Application

on:
  push:
    branches:
      - master
      - Project
  pull_request:
    branches:
      - master
      - Project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Adjust the version as needed

    - name: Restore dependencies
      run: dotnet restore Kartverk.Mvc/Kartverk.Mvc.csproj

    - name: Build
      run: dotnet build Kartverk.Mvc/Kartverk.Mvc.csproj --configuration Release --no-restore


    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
